version: '3.9'
services:
pegasus-checker:
build: .
container_name: pegasus-checker
volumes:
- ./:/app
- /dev/bus/usb:/dev/bus/usb
devices:
- /dev/bus/usb
network_mode: host
environment:
- PYTHONUNBUFFERED=1
command: ["python3", "cli.py", "scan"]